### ISSUE TITLE
Copy to clipboard in usage section

### ISSUE THREAD

**Issue by migmartri** [helm/monocular#157]
Improve the usage section by:

* Adding inputs for every command that will horizontally scroll the content
* Auto select the whole content on click and copy it to clipboard. We should show a message

**Comment by migmartri** [comment]
@Angelmmiguel 

I went ahead and tried a couple of things in my repository fork https://github.com/migmartri/monocular/commit/073653ec47463d5d9da829113f440e6bc9f7ba44

Feel free to use some of that code or discard it all-together.

### Design: 

* I put the commands inside a `<md-input>` so they are selectable and scrollable.
* Used labels for telling the user what does commands are for. 

![selection_130](https://cloud.githubusercontent.com/assets/24523/23045558/1085dc6a-f45a-11e6-82cd-12f1a9eaa885.png)

### Behavior:

Regarding the copy in clipboard what I would do is:

Once the user clicks on the command, we should:

* Select the whole command
* Show an small message saying that the command has been copied

Example of when selected:

![selection_131](https://cloud.githubusercontent.com/assets/24523/23045601/3b22c9ce-f45a-11e6-9bf7-f1912d794d63.png)

### Some other feedback

I do not specially like the background of that section so I am wondering if we can find another way to make it stand up.

**Comment by Angelmmiguel** [comment]
Thank you @migmartri! I'm going to check it. 

We can remove the dark background, but we must provide a visual differentiation from the other boxes because this is the main action of the details view.
