### ISSUE TITLE
Ingress controller causes short amount of downtime

### ISSUE THREAD

**Issue by prydonius** [helm/monocular#179]
During rolling updates, there's a short period of time where we get a 504 from nginx instead of the service. This looks to be related to https://github.com/kubernetes/contrib/issues/2098 and https://github.com/kubernetes/ingress/issues/322.

**Comment by prydonius** [comment]
I'm not sure there is much we can do about this since it's an upstream issue.

**Comment by philipbjorge** [comment]
@prydonius -- I believe this is something that can be fixed with a sleep as described at https://github.com/kubernetes/ingress/issues/322

**Comment by prydonius** [comment]
thanks for the pointer @philipbjorge, that's something you need to add to the ingress deployment config?
