### ISSUE TITLE
Link to the source of the charts

### ISSUE THREAD

**Issue by grosser** [helm/monocular#181]
I don't like blindly installing things ... and contributing to the charts would be great too

for example https://kubeapps.com/charts/stable/gitlab-ce has a link to dockerhub ... and that's it :(

**Comment by prydonius** [comment]
+1 linking to the chart source in https://github.com/kubernetes/charts would be great!

**Comment by jackfrancis** [comment]
It would benefit the UX to differentiate between source code and documentation of the underlying project itself (which is what the current links data under "Sources" references) from the source code of the chart (which is what @grosser wants a convenient reference to).

This just a note that we may want to improve the clarity of the current "Sources" sub-heading if we implement a link to the chart source.

**Comment by jackfrancis** [comment]
I don't think we're currently representing the data response w/ the information needed (source repo for chart dev). We're instead representing the registry URL, e.g.:

`"repo": {name: "stable", url: "http://storage.googleapis.com/kubernetes-charts"}`

If we want to add this add'l URL, we might want to be more explicit, for example replacing the `url` property above w/ `registryUrl`, and then adding a `sourceUrl` property to point to `https://github.com/kubernetes/charts` (for example).
