### ISSUE TITLE
Improve importing process

### ISSUE THREAD

**Issue by migmartri** [helm/monocular#187]
The current importing/indexing process has the following deficiencies.

* The importation happens sequentially and this approach was fine until the moment we added extra processing during importation time (untar and extract README files and process icons), which made this process slow.
* While we are in the importation process, no request can access to the data being imported, which means that the **API stops serving requests**.

We should improve this process by for example:

During importation:

- [x] Do not lock at the API level, keeping serving the content of the index. 
- [x] Do not clean the cache when the importation starts. keep serving the previous copy of the index. Getting replaced once the successful import finishes.
- [x] Icons downloads and processing failures are acceptable for a chart to be valid. In which case we can send this process to the background using a go routine "ignoring" its output
- [x] We should also look into default timeouts https://github.com/helm/monocular/issues/138

Regarding the deployment. In order to avoid re-importation of all the charts. We should start thinking about mounting the cache directory in a volume.

**Comment by migmartri** [comment]
@jackfrancis I'd love to get your take here.

**Comment by jackfrancis** [comment]
@migmartri I'm not able to find any unnecessary read locks on the API, but the 2nd bullet point is addressed w/ #188
