### ISSUE TITLE
Show application versions beside the Chart version (where applicable)?

### ISSUE THREAD

**Issue by solarce** [helm/monocular#192]
I am opening this issue in response to [a Twitter conversation](https://twitter.com/michellenoorali/status/834629851973722112) about some of my initial thoughts when browsing https://kubeapps.com/.

Firstly, to set the _lens_ of my perspective, I don't actively use Kubernetes or Helm at the moment, I've been keeping a close eye on both, so my perspective is mostly that of a theoretical/potential user.

I think it would be helpful if the application/database/etc version was shown, along with the Chart version, for Charts where it is appropriate.

Something like this, but much prettier.

![kubeapps](https://cloud.githubusercontent.com/assets/9660/23370676/4dd1e8ca-fcca-11e6-8fc3-c591152c479d.png)

I think have a similar, _standardized_ section in the details view of each Chart would be as helpful as well.

**Comment by migmartri** [comment]
@solarce, thanks for the feedback.

I agree that for discovery purposes, showing the APP version is important. Even more important than showing the chart one. 

AFAIK, the Helm [Chart spec](https://github.com/kubernetes/helm/blob/master/docs/charts.md#the-chartyaml-file) does not include the APP version field. So we are going to need to raise this issue upstream at the Helm repository. Would you mind [opening an issue there](https://github.com/kubernetes/helm/issues)? (let me know if you prefer me to do it instead)

Thanks again,
Miguel

**Comment by solarce** [comment]
Happy to, filed https://github.com/kubernetes/helm/issues/2035

**Comment by prydonius** [comment]
`appVersion` has been added to the spec, and we'll start populating these in the official charts repo.

**Comment by prydonius** [comment]
#293 added support for this
