### ISSUE TITLE
Add robots.txt

### ISSUE THREAD

**Issue by Angelmmiguel** [helm/monocular#214]
Now, bots are getting the 404 error page when they access to `/robots.txt`. We need to provide a correct robots.txt information. We need to include an static file and an entry in the NGINX configuration.

**Comment by nomisbeme** [comment]
https://github.com/helm/monocular/pull/243 adds a simple robots.txt file to the monocular ui project.

This resolves the 404 error Angel reported. It doesn't use nginx to serve the robots.txt file as it looks like other changes are likely there as a result of bigger changes that are coming: https://github.com/helm/monocular/issues/235

Not sure if this is useful or not, it was mostly for me to get some practice with using git and github.

**Comment by Angelmmiguel** [comment]
It was very useful @nomisbeme, I didn't have time for this issue. Thank you for the pull request and the comment.

PS: I'm gonna close this issue because the PR is merged :)
