### ISSUE TITLE
Random images retrieval error

### ISSUE THREAD

**Issue by migmartri** [helm/monocular#222]
In some cases, it seems that there is some kind of retrieval/process issue that makes logos not to be served. 

For example, calling https://kubeapps.com/api/assets/stable/gitlab-ce/0.1.5/logo-original.png could return a 404 even though the file is there.

```
ls /root/monocular/repo-data/stable/gitlab-ce/0.1.5/ -l
total 60
-rw-r--r--    1 root     root          2368 Mar 14 17:26 README.md
-rw-r--r--    1 root     root          9383 Mar 14 17:26 chart.tgz
-rw-r--r--    1 root     root         10536 Mar 14 17:27 logo-160x160-fit.png
-rw-r--r--    1 root     root         29363 Mar 14 17:27 logo-original.png
```
![pasted image at 2017_03_15 10_31 am](https://cloud.githubusercontent.com/assets/24523/23962888/d7d47d5c-09af-11e7-8107-774ac5c1b5f1.png)

We need to check if the issue is in the retrieval logic or in the processing logic.

cc/ @Angelmmiguel @prydonius

**Comment by Angelmmiguel** [comment]
@migmartri It's a weird error. I tried with [Linkerd logo](https://kubeapps.com/api/assets/stable/linkerd/0.1.1/logo-160x160-fit.png) and it works for the 50% of the requests. I'm not sure about the current configuration of kubeapps.com, but it seems some requests are processed by a backend that doesn't have the logo.

**Comment by migmartri** [comment]
Thanks @Angelmmiguel 

>  I tried with Linkerd logo and it works for the 50% of the requests

This is likely to be because we have two pods and one of those does not respond correctly.

I've done some debugging and I have verified that both pods have the same cached data:

![selection_177](https://cloud.githubusercontent.com/assets/24523/24003106/ddf530c4-0a62-11e7-89c8-bc266c77e800.png)

Then I copied the original icons from both pods and they seem to be valid images:

```
kubectl cp production/kubeapps-production-monocular-api-1478281304-4hxvk:/root/monocular/repo-data/stable/linkerd/0.1.1/logo-original.png original1.png
kubectl cp production/kubeapps-production-monocular-api-1478281304-tzpzj:/root/monocular/repo-data/stable/linkerd/0.1.1/logo-original.png original2.png
```
![selection_178](https://cloud.githubusercontent.com/assets/24523/24003099/dab63566-0a62-11e7-8521-57e8da812d99.png)
 
At this point, we should look into the assets detection code, the one in charge of lookup if the file exists and return 404 otherwise.

**Comment by migmartri** [comment]
@Angelmmiguel I have deployed some changes that adds some instrumentation in form of logging. I can not see the issue right now, but please let me know if you see it again.

**Comment by migmartri** [comment]
It does not seem to be related to the fact of having 2 pods. I have reduced the deployment to only one pod and I get the same issue. 

I have added some runtime logging to detect if we are doing any at runtime path change.

**Comment by migmartri** [comment]
I have seen the behavior in the logs. 

![selection_180](https://cloud.githubusercontent.com/assets/24523/24009300/d5524d32-0a74-11e7-839c-ceb815703d03.png)

**Comment by Angelmmiguel** [comment]
That's really weird because the path of the image is the same in both cases 🤔. Can it be related with `os.Stat` method? Also, we are calling twice the method in every request

**Comment by migmartri** [comment]
I was wrong, I was actually looking into another cluster (dumb).

It seems that the problem is related to timeouts while pulling icons. I am going to increase the timeout default time.

![selection_181](https://cloud.githubusercontent.com/assets/24523/24011134/2f6f5a6c-0a7a-11e7-9131-8f599dcf9aa5.png)

**Comment by migmartri** [comment]
My working theory is that since I added the parallel chart retrieval the timeout is not enough. 

I have:

* Increases the timeout limit
* Reduced the number of workers
* Logged download errors for further tweaking
