### ISSUE TITLE
Helm install command does not work

### ISSUE THREAD

**Issue by migmartri** [helm/monocular#227]
Copied from the readme:
```
helm install stable/nginx-ingress --version 0.3.1
Error: file "stable/nginx-ingress" not found
```

Removing the version works.

**Comment by prydonius** [comment]
Shouldn't this be filed in https://github.com/kubernetes/helm?

**Comment by migmartri** [comment]
@prydonius, I have not verified yet that this is a Helm issue. I'll escalate it if that's the case.

**Comment by migmartri** [comment]
According to the CLI the latest version is 0.3.0 but in Monocular we have 0.3.1

```
 helm search nginx-ingress
NAME                    VERSION DESCRIPTION                                       
stable/nginx-ingress    0.3.0   An nginx Ingress controller that uses ConfigMap...
stable/nginx-lego       0.2.0   Chart for nginx-ingress-controller and kube-lego  
```

**Comment by migmartri** [comment]
It seems that I needed to update my repository local cache.

```
 helm update
 helm search nginx-ingress
NAME                    VERSION DESCRIPTION                                       
stable/nginx-ingress    0.3.1   An nginx Ingress controller that uses ConfigMap...
```

This looks to me like an usability issue, @technosophos, is this something that the Helm team is aware?

I am wondering if from our side (Monocular) we should add the helm update command in the CLI instructions, @Angelmmiguel what do you think?

**Comment by Angelmmiguel** [comment]
@migmartri Does it affect to the latest version too? I mean, if I want to install the latest version of a chart, should I run `helm update` before? If this statement is true, I think we have to add this to the instructions. However, if this is only required for a specific version we can add it in that case.

**Comment by prydonius** [comment]
@migmartri the issue here was forgetting to run `helm repo update` before running the command, right? If so, I think this can be closed out.

**Comment by jorgemorando** [comment]
hi guys ... this thing is still happening and no, not forgetting helm repo update

```
root@k8s-master:~# helm search nginx-ingress
NAME                    CHART VERSION   APP VERSION     DESCRIPTION
stable/nginx-ingress    0.16.1          0.13.0          An nginx Ingress controller that uses ConfigMap...
stable/nginx-lego       0.3.1                           Chart for nginx-ingress-controller and kube-lego
root@k8s-master:~# helm install stable/nginx-ingress
Error: no available release name found
root@k8s-master:~# rm -rf /root/.helm
root@k8s-master:~# helm repo update
Error: Couldn't load repositories file (/root/.helm/repository/repositories.yaml).
You might need to run `helm init` (or `helm init --client-only` if tiller is already installed)
root@k8s-master:~# helm init --client-only
Creating /root/.helm
Creating /root/.helm/repository
Creating /root/.helm/repository/cache
Creating /root/.helm/repository/local
Creating /root/.helm/plugins
Creating /root/.helm/starters
Creating /root/.helm/cache/archive
Creating /root/.helm/repository/repositories.yaml
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
Adding local repo with URL: http://127.0.0.1:8879/charts
$HELM_HOME has been configured at /root/.helm.
Not installing Tiller due to 'client-only' flag having been set
Happy Helming!
root@k8s-master:~# helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈
root@k8s-master:~# helm install stable/nginx-ingress
Error: no available release name found
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
$ helm version
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```
any thoughts?

**Comment by Shuanglu** [comment]
Similar issue.

testshuang@testSLJumpbox:~/AKS/IngressTest$ helm install stable/nginx-ingress  --debug
[debug] Created tunnel using local port: '37445'

[debug] SERVER: "127.0.0.1:37445"

[debug] Original chart version: ""
[debug] Fetched stable/nginx-ingress to /home/testshuang/.helm/cache/archive/nginx-ingress-0.18.0.tgz

[debug] CHART PATH: /home/testshuang/.helm/cache/archive/nginx-ingress-0.18.0.tgz

Error: no available release name found
testshuang@testSLJumpbox:~/AKS/IngressTest$ helm version
Client: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}

**Comment by prydonius** [comment]
@jorgemorando this is likely an RBAC issue if your cluster has RBAC. Take a look at https://github.com/kubernetes/helm/blob/master/docs/rbac.md
