### ISSUE TITLE
Update monocular backend to respect /api/ path

### ISSUE THREAD

**Issue by dcberg** [helm/monocular#231]
Today the monocular ingress is using the ` ingress.kubernetes.io/rewrite-target:` annotation to rewrite `/api/` to `/`. This limits portability of monocular to only ingress controllers that support the rewrite annotation.

**Comment by prydonius** [comment]
cc @migmartri - I think we talked about this before? Given that the frontend assumes the prefixed path, I don't think it would be a stretch for the backend to assume the prefixed path too. What do you think?

**Comment by migmartri** [comment]
@dcberg good point, what ingress controller are you planning on running monocular with?

@prydonius yeah, I think that adding /api to backend's basepath seems reasonable.

**Comment by dcberg** [comment]
Sorry for the delay @migmartri 

We have our own ingress controller that is based on nginx. Our current implementation doesn't support the rewrite annotation; however, we are adding the support.

**Comment by mlaccetti** [comment]
We're using Traefik as the ingress controller, which doesn't seem to understand the `rewrite-target` annotation. It has a custom annotation (`traefik.frontend.rule.type: pathprefixstrip`), but it applies it to all paths, which mangles the UI paths.

**Comment by prydonius** [comment]
@mlaccetti @dcberg I just added support for specifying separate hostnames for the API and frontend via the [`ui.backendHostname`](https://github.com/helm/monocular/blob/master/deployment/monocular/values.yaml#L68) property which configures the API location and the [`api.config.cors.allowed_origins`](https://github.com/helm/monocular/blob/master/deployment/monocular/values.yaml#L37) property which configures CORS to accept requests from your UI hostname.

With these you can avoid using a `/api` path and instead use subdomains such as `api.monocular.local` and `monocular.local`:

```
helm install ./deployment/monocular --set ui.backendHostname=https://api.monocular.local,api.config.cors.allowed_origins={http://monocular.local}
```

**Comment by mlaccetti** [comment]
This will require changing the ingress to add two different domains, then?

**Comment by prydonius** [comment]
@mlaccetti yes, I haven't changed the ingress template in the chart for this, but I was thinking of adding an `ingress.enabled` flag which can be used to use your own ingress. I will add this in combination with updating the template to use the hostnames if they are set.

**Comment by prydonius** [comment]
@mlaccetti I have added an `ingress.enabled` flag to the chart. If you need to serve Monocular on separate domains, at the moment, you will need to setup your own Ingress resource independently of the chart.
