### ISSUE TITLE
no charts loaded from local helm repo

### ISSUE THREAD

**Issue by hybmg57** [helm/monocular#236]
Hi,

I've run local helm repo and ran monocular on minikube. Monocular seems to run fine but it doesn't display any results. When I go to http://monocular-api/v1/charts (or http://monocular-ui/api/v1/charts) I get below:

```
{
  data: null
}
```

When I visit my local helm repo which is served using `helm serve` it seems to return fine with the HTML page returned representing "Chart Repository" `index.yaml` file generated by helm.

How do I make this work with local `helm` server?

**Comment by prydonius** [comment]
cc @migmartri

**Comment by hybmg57** [comment]
Ok so looks like it worked. It seems though some scheduler is running to fetch some index data

**Comment by Angelmmiguel** [comment]
Great @hybmg57. The API takes some time to get all the metadata and process the icons of all available charts.
