### ISSUE TITLE
Refresh interval needs to be configurable.

### ISSUE THREAD

**Issue by kumarom** [helm/monocular#237]
As of now, refresh interval is hard-coded to 3600 sec [here](https://github.com/helm/monocular/search?utf8=%E2%9C%93&q=3600&type=). It would be desirable to **override** this value either using config file or using env variable.

**Comment by prydonius** [comment]
I think this is a good idea.

Currently API configuration is passing in using the `monocular.yaml` file (the chart uses a [configmap](https://github.com/helm/monocular/blob/master/deployment/monocular/values.yaml#L22)) and gets loaded with the [config package](https://github.com/helm/monocular/tree/master/src/api/config).

@kumarom as you mentioned on Slack, if you'd like to work on this that would be really great :)

**Comment by kumarom** [comment]
#238 merged. Hence closing this issue.
