### ISSUE TITLE
Support customizing values.yaml on new deployment

### ISSUE THREAD

**Issue by tarasglek** [helm/monocular#245]
It would be handy to present values.yaml for editing when clicking 'install'. This would let one set passwords, networking configuration, etc.

**Comment by prydonius** [comment]
:+1: this would be great

**Comment by Angelmmiguel** [comment]
I totally agree with you :+1:

**Comment by tarasglek** [comment]
So if my understanding is correct. The way to resolve this would be to:
1. Switch tiller to use REST/swagger instead-of/in-addition-to gRPC
2. Have tiller use structured data instead of passing strings designed for kubectl(eg default to json or yaml output). This is an aside referring to https://github.com/helm/monocular/issues/244
3. Get rid of chart management aspect of monocular rest server, talk to tiller directly(or maybe proxy it), but not reimplement rpc manually.

![protocols](https://user-images.githubusercontent.com/857083/27710820-d945a4da-5cd5-11e7-814e-62f1301dd006.png)

**Comment by felixPG** [comment]
Any advance wih this? This give to monocular more scalability!!

**Comment by kelvinblood** [comment]
Any advance wih this? 
convenient feature!

**Comment by Stolr** [comment]
+1 Would be awesome

**Comment by michaelgaida** [comment]
+1

**Comment by zhangshuiyong** [comment]
+1

**Comment by prydonius** [comment]
Closing this out at Monocular no longer includes in-cluster features (https://github.com/helm/monocular#looking-for-an-in-cluster-application-management-ui). If this is what you're looking, checkout [Kubeapps](https://github.com/kubeapps/kubeapps) which supports this.
