### ISSUE TITLE
Build and push images from Travis CI

### ISSUE THREAD

**Issue by prydonius** [helm/monocular#271]
On pushes to master, build and push development/latest tags.

On tagged releases, build and push tagged images.

**Comment by sebgoa** [comment]
push images is fine, but there needs to be a github release (an all-in-one manifest for example). Look at how Gus releases ksonnet sealed secret: https://github.com/ksonnet/sealed-secrets/releases

It is very handy for users. No need to clone a repo or pre-install helm ...

**Comment by prydonius** [comment]
@sebgoa I created #272
