### ISSUE TITLE
Search function not working (minikube)

### ISSUE THREAD

**Issue by todkap** [helm/monocular#277]
Attempting to run the latest monocular and hitting an issue with search.

I am using the following command..
API_TAG=1 API_NAME="https://192.168.99.101:31407" UI_TAG=1 ./deploy_install.sh
The API_NAME is constructed using the minikube IP and the NodePort for the Ingress SSL port.

The UI paints fine but when I attempt to search, I get errors in my javascript.
> EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'map' of null
> TypeError: Cannot read property 'map' of null
>     at https://192.168.99.101:31407/main.bdb0b927465b27053515.bundle.js:5:24358
>     at Array.filter (native)
>     at e.project (https://192.168.99.101:31407/main.bdb0b927465b27053515.bundle.js:5:24160)
>     at e._next (https://192.168.99.101:31407/vendor.8ee2fe2025f290cf36e9.bundle.js:317:9079)
>     at e.next (https://192.168.99.101:31407/vendor.8ee2fe2025f290cf36e9.bundle.js:8:3990)
>     at t._subscribe (https://192.168.99.101:31407/main.bdb0b927465b27053515.bundle.js:5:23772)
>     at t.subscribe (https://192.168.99.101:31407/vendor.8ee2fe2025f290cf36e9.bundle.js:1:354)
>     at t.call (https://192.168.99.101:31407/vendor.8ee2fe2025f290cf36e9.bundle.js:317:8842)
>     at t.subscribe (https://192.168.99.101:31407/vendor.8ee2fe2025f290cf36e9.bundle.js:1:323)
>     at t.searchCharts (https://192.168.99.101:31407/main.bdb0b927465b27053515.bundle.js:5:17758)
>     at https://192.168.99.101:31407/main.bdb0b927465b27053515.bundle.js:5:17634
>     at e._next (https://192.168.99.101:31407/vendor.8ee2fe2025f290cf36e9.bundle.js:1:787)
>     at e.__tryOrSetError (https://192.168.99.101:31407/vendor.8ee2fe2025f290cf36e9.bundle.js:8:5764)
>     at e.next (https://192.168.99.101:31407/vendor.8ee2fe2025f290cf36e9.bundle.js:8:4943)
>     at e._next (https://192.168.99.101:31407/vendor.8ee2fe2025f290cf36e9.bundle.js:8:4319)

I see the helm charts being pulled are all tagged 'latest'.   Do you have tags for stable?

**Comment by todkap** [comment]
Possibly a documentation issue.   
I was able to get this to work properly by specifying the tags as "latest" versus the product documentation of "1"
API_TAG=latest UI_TAG=latest API_NAME="https://192.168.99.101:30006"  ./deploy_install.sh

**Comment by prydonius** [comment]
@todkap thanks for pointing it out, with the 2.1 release I plan to improve the release process and documentation

**Comment by todkap** [comment]
Great news.. 
I wrote up a quick script that I was working with locally.  Welcome to use any of it.  I felt I needed to be able to quickly clear up prior deployments since the default helm install creates new unique names on each install.

```
echo "Cleaning up prior deployments"
kubectl delete ingress --all ## works fine for now but may not be ideal

kubectl delete deployments --selector=app=nginx-ingress
kubectl delete services --selector=app=nginx-ingress
kubectl delete pods --selector=app=nginx-ingress

kubectl delete deployments -l chart=monocular-0.4.0
kubectl delete services -l chart=monocular-0.4.0

# helm init --upgrade
helm install stable/nginx-ingress

statusCheck="NOT_STARTED";
echo 'Checking on status of helm install of nginx'
while [ "$statusCheck" != "" ] ; do
	statusCheck=$(kubectl get pods  -o json | jq '.items[].status.phase' | grep -v "Running")
	echo "statusCheck: $statusCheck"
done
echo 'Completed helm install of nginx'

ipAddress=$(minikube ip)
port=$(kubectl get services  -o json --selector=app=nginx-ingress,component=controller | jq '.items[0].spec.ports | to_entries[] | select(.value.name=="https")' |  jq '.value.nodePort')

echo "ipAddress: " $ipAddress;
echo "port: " $port;

echo "Installing latest tagged UI and API for Monocular using API_NAME: https://$ipAddress:$port"
API_NAME="https://$ipAddress:$port" API_TAG=latest UI_TAG=latest ./deploy_install.sh
echo "We should be available at: https://$ipAddress:$port once the pods are all running"
```
