### ISSUE TITLE
Overriding releasesEnabled disables API_NAME override

### ISSUE THREAD

**Issue by todkap** [helm/monocular#278]
In issue #277, I was attempting to override some of the default settings from the CLI.   The default setting today for Monocular is to disable releasesEnabled.   I was able to enable deployments by setting the values.yaml property to true but the command line appears to override my API_NAME setting for some reason (getting CORS errors when I add in VALUES_OVERRIDE thus appearing to ignore my API_NAME).    This might be a user error but wanted to document this in case others hit the same issue.  

API_NAME="https://$ipAddress:$port" API_TAG=latest UI_TAG=latest VALUES_OVERRIDE="api.config.releasesEnabled=true" ./deploy_install.sh

**Comment by prydonius** [comment]
@todkap where did you get the API_NAME env var from, I don't see this in the docs or scripts?

In order to fix the CORS errors you need to set the `api.config.cors.allowed_origins` property, e.g.:

```
VALUES_OVERRIDE="api.config.releasesEnabled=true,ui.service.internalPort=8080,ui.backendHostname=http://$apiIpAddress:$port,api.config.cors.allowed_origins={http://$uiIpAddress:$port}"
```

You might need to make sure you're using the `bitnami/monocular-ui` and `bitnami/monocular-api` images rather than the images from GCR. The deployment scripts should be updated

**Comment by todkap** [comment]
@prydonius 
https://github.com/helm/monocular/blob/master/docs/deployment.md#deploy-for-the-first-time

> Arguments
> 
> Required
> 
> API_TAG: Image tag to be used on the API tier, it will be appended to API_IMAGE
> UI_TAG: Image tag to be used on the API tier. It will be appended to UI_IMAGE
> Optional
> 
> API_NAME (default: gcr.io/helm-ui/monocular-api)
> UI_NAME (default: gcr.io/helm-ui/monocular-ui)
> RELEASE_NAME (default: Helm's provided random name) Helm release name.
> VALUES_OVERRIDE (default: api.image.repository=${API_IMAGE},api.image.tag=${API_TAG},ui.image.repository=${UI_IMAGE},ui.image.tag=${UI_TAG}) Helm values to be overridden (helm install --set $VALUES_OVERRIDE)
> HELM_OPTS (default: no value) Extra options to be passed to the helm command i.e --dry-run --debug

**Comment by todkap** [comment]
ohh.. that is the HELM location.  Wondering how this was working for me in my testing for CORS.

**Comment by prydonius** [comment]
@todkap ah I see, that's the docker image repo (pulling from google container registry), however it doesn't look like the deployment scripts actually use them, rather they just hardcode the image repo: https://github.com/helm/monocular/blob/master/deployment/common.sh#L5

To be honest, the deployment scripts are a bit of a mess. I've been using `helm install/upgrade` directly and I'm not sure these scripts provide much value on top of that. I suggest you try to install it with:

```
helm install ./deployment/monocular --set api.config.releasesEnabled=true,ui.backendHost=https://$API_HOST:$API_PORT,api.config.cors.allowed_origins={$UI_HOST:$UI_PORT}
```

Note the curly brackets round the UI host/port are needed as this is an array value.

Also, it looks like, from your script in #277, you're using the nginx-ingress controller, so you shouldn't even need to set ui.backendHost or api.config.cors.allowed_origins, it should just work out of the box on the same ingress domain.

**Comment by todkap** [comment]
Let me run again locally and get the URL that it tries to go to without me setting this value.  I too thought the ingress should just handle this but locally it did not for me (also one of my teammates hit a similar issue).  If it works after retesting, I will close this out as user error.

**Comment by prydonius** [comment]
Ah, I think I spotted the bug... it's trying to point to `http://localhost:8080` which is the development url. Changing the default `ui.backendHost` in the chart to `/api` will fix this. Will send a PR.

**Comment by todkap** [comment]
Looks like the key aspect was to specify latest for my testing (not the API_NAME as I combined a few things in my testing). 
`API_TAG=latest UI_TAG=latest ./deploy_install.sh`
looks to be great when used in combination with the ingress endpoint and also has the deployment.

You are correct that the scripts themselves need more love.  When I use the following
`API_TAG=latest UI_TAG=latest VALUES_OVERRIDE="api.config.releasesEnabled=true" ./deploy_install.sh`
I get the following (whihc is what you had in your comment just prior)..

> vendor.433fc02cbba61bee4b7c.bundle.js:1475 Mixed Content: The page at 'https://192.168.99.100:30331/charts' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://localhost:8080/v1/charts'. This request has been blocked; the content must be served over HTTPS.

I can migrate over to using the helm command directly but I think others will hit this too.  It is great to document these limitations I think.

**Comment by prydonius** [comment]
@todkap I updated the chart to use the correct API location. Can you confirm that if you install the chart now with just:

```
helm install ./deployment/monocular --set api.config.releasesEnabled=true
```

**Comment by todkap** [comment]
Pulled the latest code and ran this command @prydonius.  When I do so, I am able to click on the Deployments button and then "new deployment" but it just returns to the list of items already in the catalog.

**Comment by prydonius** [comment]
@todkap are you able to see a list of the charts? You should be able to click on a particular chart and then see the install button.

**Comment by todkap** [comment]
Yes. that part works just fine.  I thought this would allow me to publish new items into the catalog.

**Comment by prydonius** [comment]
Ah no, the "Deployments" tab is for seeing charts installed in the cluster, but Monocular can currently only read from existing chart repositories. It cannot currently write to and manage them.

**Comment by prydonius** [comment]
@todkap going to close this one out, feel free to open a new issue if you have any other questions/issues
