### ISSUE TITLE
API - /charts/{repo}/{chart-name} observations

### ISSUE THREAD

**Issue by migmartri** [helm/monocular#29]
If you access for example to `http://localhost:8080/v1/charts/stable/redmine` you get the following output.

```
{
data: {
  attributes: {
    created: "2016-10-06T16:23:20.499814565-06:00",
    description: "A flexible project management web application.",
    digest: "99c76e403d752c84ead610644d4b1c2f2b453a74b921f422b9dcb8a7c8b559cd",
    home: "https://k8s.io/helm",
    name: "redmine",
    repo: "stable",
    sources: [
      "https://github.com/kubernetes/charts/redmine"
   ],
   urls: [
     "https://storage.googleapis.com/kubernetes-charts/redmine-0.0.1.tgz"
  ]
  },
  id: "stable/redmine",
  links: {
    latest: "/v1/charts/stable/redmine/0.0.1"
  },
  type: "chart"
 }
}
```

#### Latest Link
For example the latest link points to `/v1/charts/stable/redmine/0.0.1` but I am wondering if it should include the `/versions` namespace, i.e /v1/charts/stable/redmine/versions/0.0.1

#### Digest

Shouldn't this route return a non-version Chart resource. If that's the case, shouldn't we remove digest and the Urls?

**Comment by jackfrancis** [comment]
I think these issues should address all of this:

- https://github.com/helm/monocular/issues/33
- https://github.com/helm/monocular/issues/36

The only version info that the general chart route endpoint should deliver is a link to the "latest" version endpoint.

**Comment by jackfrancis** [comment]
I'm recommending that we keep the fully populated, versioned metadata inside the data response for `/v1/charts/{:repo}/{:chart}`. Everything will be in there to be consumed when it's appropriate to source data from a "get latest chart version" authoritative endpoint.

We'll also include the canonical link for that version in the `links` object, in its `latest` property.
