### ISSUE TITLE
API - /charts/{repo}/{chartName} <=> /charts/{repo}/{chartName}/versions

### ISSUE THREAD

**Issue by migmartri** [helm/monocular#30]
Apparently based on my tests `http://localhost:8080/v1/charts/stable/redmine` and `http://localhost:8080/v1/charts/stable/redmine/versions` return both the same result and the same kind of object (chart).

Is this a desired behavior? Maybe for the /stable/redmine/versions API endpoint, we should change the type to `chartVersion`, and for the `/stable/redmine` case, remove the version specific attributes as suggested here https://github.com/helm/monocular/issues/29.

What's your take on this?

**Comment by jackfrancis** [comment]
They should not return the same type of data. This example route:

- `http://localhost:8080/v1/charts/stable/redmine`

... should return a non-version-specific representation of the chart, with a link to the "latest" version

This example route:

- http://localhost:8080/v1/charts/stable/redmine/versions

... should return a collection of all specific chart+version data representations, but without the "latest" link present.

**Comment by jackfrancis** [comment]
See #29 for more info. But, in summary, I think the easiest path forward is to in fact include the same kind of versioned data for all endpoints, with the exception that the `/v1/charts/{:repo}/{:chart}` endpoint will include a `links.latest` canonical link to the returned version.
