### ISSUE TITLE
Ingress class hardcoded

### ISSUE THREAD

**Issue by mikelorant** [helm/monocular#300]
The ingress class has been hard coded to nginx.

https://github.com/helm/monocular/blob/master/deployment/monocular/templates/ingress.yaml#L11

This should be removed and the annotation example should show the correct syntax.

**Comment by prydonius** [comment]
@mikelorant there's a PR open #297 to do this, can you give that a quick review?

**Comment by prydonius** [comment]
Fixed in #297 which has been released as chart version 0.4.4.

**Comment by mikelorant** [comment]
Confirmed the solution in 0.4.4 is what we needed.

**Comment by prydonius** [comment]
thanks @mikelorant
