### ISSUE TITLE
Create Helm Chart for deploying backend/frontend to production

### ISSUE THREAD

**Issue by migmartri** [helm/monocular#34]
Create a Helm Chart that allows the configuration of:
- Helm Chart repositories from which the backend is going to feed from (low prior)
- Backend Hostname to be used by the UI
- Common persistence and services exposure settings

**Comment by migmartri** [comment]
cc @prydonius

**Comment by prydonius** [comment]
The first version will have two tiers for the backend and frontend. The frontend will be built into an nginx container, and the backend will just run the compiled API binary.

The initial Chart may hardcode an address for accessing the backend, but this should later be configurable.

**Comment by Angelmmiguel** [comment]
I agree with @prydonius. Frontend is just a bunch of static files. Also, we can optimize it moving all the assets to a CDN in the future.

**Comment by migmartri** [comment]
https://github.com/helm/monocular/pull/76
