### ISSUE TITLE
How do I use an external MongoDB instead?

### ISSUE THREAD

**Issue by chrisfelix82** [helm/monocular#404]
I want to use an external database as a service MongoDB instance instead of the cluster one.  How would I do that?  Thanks.  

Also not sure why the MongoDB in the helm release is not starting up.  I get the following error: 

```
Welcome to the Bitnami mongodb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing mongodb
Error executing 'postInstallation': Group '4294967294' not found
```

**Comment by prydonius** [comment]
Hmm, the chart currently doesn't allow you to do this. It is possible to make it optional using a [conditional in requirements.yaml](https://github.com/kubernetes/helm/blob/master/docs/charts.md#tags-and-condition-fields-in-requirementsyaml).

Not sure why the MongoDB container is failing for you, what kind of storage provisioning do you have?

**Comment by chrisfelix82** [comment]
The storage provisioner is on IBM container service.  I believe that it is NFS.

**Comment by chrisfelix82** [comment]
Regardless of getting mongodb working in the cluster, it may be worth adding the option for an ExternalName service for a remote MongoDB managed instance.

**Comment by prydonius** [comment]
@chrisfelix82 yeah, I agree. Some charts have already adopted the ability to specify an external database (https://github.com/kubernetes/charts/blob/master/stable/ghost/values.yaml#L72).

Btw, you may also want to check out https://github.com/kubeapps/kubeapps, it doesn't currently support the external MongoDB, but this is where the future of this project is going.

**Comment by drekle** [comment]
I have this same issue, using a glusterfs default storage class.  I have been switching the image used in the mongo deployment manually.

**Comment by zucher** [comment]
Hi,

How to solve this issue regarding monocular deployment in IBM Container Service context ?

Thank you
