### ISSUE TITLE
Support different kube contexts

### ISSUE THREAD

**Issue by hiscal2015** [helm/monocular#417]
Hi, 

We're using different context to manage multiple Kubernetes clusters, does monocular support context switch so it can deploy to different clusters?

https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/

**Comment by prydonius** [comment]
@hiscal2015 Monocular will automatically pick up the context of the cluster it's running in, so you would just need to deploy it to each cluster you want to use it on. It's not possible to configure Monocular on one cluster to install charts in external cluster(s) yet.

**Comment by hiscal2015** [comment]
@prydonius I have multiple Kubernetes clusters and I want to run monocular outside of Kubernetes, if it supports context switch that would be wonderful.

**Comment by prydonius** [comment]
@hiscal2015 thanks for the explanation. I think the only way for you to achieve this today would be to mount a kubeconfig into `./kube/config` in the same way that the docker-compose file does for development (https://github.com/kubernetes-helm/monocular/blob/master/docker-compose.yml#L20). However, you will need to run multiple instances of Monocular per kubeconfig.

I'll keep the request to support multiple kubeconfigs open, but I don't think we'll get round to implementing this anytime soon, and also not sure if it's the best direction for the project as cluster-based installs are much easier to manage.

**Comment by oleborne** [comment]
Hi @prydonius 

I'm trying to run monocular outside a k8s cluster, in a docker-compose env on my workstation, for dev activities (my app is acting as a chart repo so monocular must be able to access the server running on localhost).
I tried to inject a proper `kubeconfig` in `/root/.kube/config` as you just described but when triggering a release, monocular is still searching for tiller in localhost:8080.

Any idea on how I can have this working?

**Comment by prydonius** [comment]
@oleborne you likely need to set tillerPortForward to true and/or unset tillerHost in your config: https://github.com/kubernetes-helm/monocular/blob/master/docs/config.example.yaml#L28
