### ISSUE TITLE
monocular CrashLoopBackOff with mongo in pending 

### ISSUE THREAD

**Issue by kumiisc** [helm/monocular#419]
I have installed monocular using helm and the pod seems to crashloop.
monogo db pod is in pending status. No logs in monogo pod.
Can some  guide where the issue is ?

monocular-mongodb-3297385788-2sf4d                    0/1       Pending            0          19m
monocular-monocular-api-4206649573-6pmm6              0/1       CrashLoopBackOff   8          19m
monocular-monocular-api-4206649573-vql6m              0/1       CrashLoopBackOff   8          19m
monocular-monocular-prerender-2060794013-n8k1v        1/1       Running            0          19m
monocular-monocular-ui-2374440452-rglv5               1/1       Running            0          19m
monocular-monocular-ui-2374440452-wwq7p               1/1       Running            0          19m
ngix-nginx-ingress-controller-593623324-wsnkt         1/1       Running            0          22m
ngix-nginx-ingress-default-backend-2369107551-j9253   1/1       Running            0          22m
ui-kubernetes-dashboard-2399210613-1tf6r              1/1       Running            0          20h

**Comment by prydonius** [comment]
Hey @kumiisc, this is most likely because the PVC for MongoDB isn't getting bound. Can you check `kubectl get pvc` and verify that? Do you have a storage class setup in your cluster?

**Comment by itzamnamx** [comment]
I have the same issue, and I got a PVC in my cluster using GlusterFS

**Comment by prydonius** [comment]
@itzamnamx were you able to try the fix in https://github.com/kubernetes/charts/issues/2488#issuecomment-368388462?

**Comment by itzamnamx** [comment]
@prydonius I have apply that fix in a forked version of MongoDB https://github.com/fintecheando/charts/blob/master/stable/mongodb/templates/deployment.yaml but later how can I make reference in Monocultar to take that image?

Regards

**Comment by prydonius** [comment]
@itzamnamx you can fork the chart and apply it there until the change is accepted upstream

**Comment by itzamnamx** [comment]
I have just a silly newbie question. The chart where the change should be apply is the MongoDB and then in the Monocular I have to make reference to the MongoDB that I have changed. Right?

⁣Enviado desde TypeApp ​

**Comment by prydonius** [comment]
@itzamnamx yes, for the forked chart you have two options. You can remove the requirements.yaml/lock files, and place your modified MongoDB chart inside the `charts/` directory at the root of the chart. Or if you have a chart repository, you can change the URL and version in requirements.yaml (https://github.com/kubernetes-helm/monocular/blob/master/deployment/monocular/requirements.yaml#L4).

**Comment by iam-merlin** [comment]
I just try to install the chart and I've the same issue.

I forked the project, update the mongodb dep to 4.0.4 and it works perfectly, do you want a PR?

**Comment by prydonius** [comment]
@iam-merlin sure a PR for that would be great! Do you know what change in MongoDB 4.0.4 that helps fix this?

**Comment by iam-merlin** [comment]
@prydonius to be honest, I don't know xD.

I just saw that your deps were outdated and I simply update it.

**Comment by prydonius** [comment]
@iam-merlin fair enough, I think it makes sense to update it so happy to accept a PR for that!

**Comment by iam-merlin** [comment]
@prydonius done
