### ISSUE TITLE
Technical SEO requirements 

### ISSUE THREAD

**Issue by migmartri** [helm/monocular#45]
Check that the UI comply with the minimal basic SEO technical requirements in terms of labels, meta, content, URL's, etc.

**Comment by Angelmmiguel** [comment]
I'm going to start working on this :)

**Comment by Angelmmiguel** [comment]
I investigated the different ways to add metadata to the HTML head in Angular2. It seems most people uses a library called [ng2-meta](https://github.com/vinaygopinath/ng2-meta). This library provides use a Service to update the metadata from components. Also, we can set values by default. 

I think it fits our requirements, so I'm going to add it to the project and start defining the tags for the different views.

**Comment by Angelmmiguel** [comment]
After reading more about angular/universal, the required features are covered when we pre-render the application in the server. So, before continue with this issue, we must define how we are going to reach a friendly rendering for SEO in #44.

**Comment by Angelmmiguel** [comment]
PR: #91
