### ISSUE TITLE
Unable to connect to Mongodb

### ISSUE THREAD

**Issue by rjain15** [helm/monocular#528]
I install using helm 
`helm install monocular/monocular`

The PVC is created, I have the nginx ingress controller. I see the Pods, Services, PVC created and bound
`kubectl get pvc` shows the PVC on 9G and status as bound

But the API pod is crashing. Checking the Error logs, I see a fatal error message
"unable to connect to MongoDB" host="lumpt-ra-mongodb:27017"

My question, do I need to deploy a mongodb in another pod? I don't see any mongodb pod?

Thanks, 
Rajesh

**Comment by rjain15** [comment]
⇒  helm status monocular                            
LAST DEPLOYED: Wed Sep 26 18:02:44 2018
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/Secret
NAME               TYPE    DATA  AGE
monocular-mongodb  Opaque  1     47s

==> v1/ConfigMap
NAME                            DATA  AGE
monocular-monocular-api-config  1     47s
monocular-monocular-ui-config   1     47s
monocular-monocular-ui-vhost    1     47s

==> v1/PersistentVolumeClaim
NAME               STATUS  VOLUME                                    CAPACITY  ACCESS MODES  STORAGECLASS  AGE
monocular-mongodb  Bound   pvc-e56aef3b-c1d7-11e8-b182-4201c0a8140a  9G        RWO           standard      47s

==> v1/Service
NAME                           TYPE       CLUSTER-IP      EXTERNAL-IP  PORT(S)       AGE
monocular-mongodb              ClusterIP  10.100.200.35   <none>       27017/TCP     47s
monocular-monocular-api        NodePort   10.100.200.219  <none>       80:30312/TCP  47s
monocular-monocular-prerender  NodePort   10.100.200.84   <none>       80:32281/TCP  47s
monocular-monocular-ui         NodePort   10.100.200.131  <none>       80:32536/TCP  47s

==> v1beta1/Deployment
NAME                           DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
monocular-mongodb              1        0        0           0          47s
monocular-monocular-api        2        2        2           0          47s
monocular-monocular-prerender  1        1        1           1          47s
monocular-monocular-ui         2        2        2           2          47s

==> v1beta1/Ingress
NAME                 HOSTS  ADDRESS  PORTS  AGE
monocular-monocular  *      80       47s

==> v1/Pod(related)
NAME                                            READY  STATUS            RESTARTS  AGE
**monocular-monocular-api-84546494db-8grm6        0/1    CrashLoopBackOff  1         47s
monocular-monocular-api-84546494db-mxshq        0/1    CrashLoopBackOff  1         47s**
monocular-monocular-prerender-7948c67fdf-pnfz6  1/1    Running           0         47s
monocular-monocular-ui-587d5886d9-7ctrj         1/1    Running           0         47s
monocular-monocular-ui-587d5886d9-qhf98         1/1    Running           0         47s


NOTES:
The Monocular chart sets up an Ingress to serve the API and UI on the same
domain. You can get the address to access Monocular from this Ingress endpoint:

  $ kubectl get ingress monocular-monocular

Visit https://github.com/helm/monocular for more information.

**IMPORTANT**: Releases are enabled, which will allow anybody with access to the running instance to create, list and delete any Helm release existing in your cluster.
This feature is aimed for internal, behind the firewall deployments of Monocular, please plan accordingly. To disable this, re-install Monocular setting api.config.releasesEnabled=false.


Monocular expects tiller-deploy to be found in namespace kube-system
`

**Comment by rjain15** [comment]
I will have to dig into this, https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#securitycontextdeny

**Comment by prydonius** [comment]
@rjain15 ah interesting, I think by default MongoDB is setting the security context to run as a non-root 1001 user.

**Comment by rjain15** [comment]
I changed the setting on the controller to allow privileged user ,and it started up the pod. But now I facing another issue. For some reason their seems to be a readiness probe which is trying to connect to 127.0.0.1:27017

----

error
monocular-mongodb-7bf4bfb798-2jh9w
vm-47dd3a98-7580-412d-665c-560a531b6a00
Waiting: CrashLoopBackOff
3
3 minutes
 0
 40 Ki
pod has unbound PersistentVolumeClaims (repeated 3 times)
Readiness probe failed: MongoDB shell version v3.6.6 connecting to: mongodb://127.0.0.1:27017 2018-09-27T00:18:41.685+0000 W NETWORK [thread1] **Failed to connect to 127.0.0.1:27017**, in(checking socket for error after poll), reason: Connection refused 2018-09-27T00:18:41.685+0000 E QUERY [thread1] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed : connect@src/mongo/shell/mongo.js:251:13 @(connect):1:6 exception: connect failed

**Comment by prydonius** [comment]
@rjain15 hmm, that shouldn't be failing. Are you able to run MongoDB by itself (helm install stable/mongodb)?

**Comment by rjain15** [comment]
I believe this is a problem with the mongodb from the bitnami repo. I
changed the repo to  https://kubernetes-charts.storage.googleapis.com and
used the mongodb from this repo and it worked. I also tried running on GKE
to double check if this was on my local cluster, and it was failing on GKE.

So here is my analysis, I haven't compared what is the difference between
the chart on the bitnami repo and the kubernetes-charts repo.

I also tried kubeapps, and it was running into the same readiness probe
issue in Mongodb.

**Comment by prydonius** [comment]
@rjain15 we're pointing to the chart from that repo: https://github.com/helm/monocular/blob/master/chart/monocular/requirements.yaml#L4 but perhaps there's a newer version we can upgrade to that fixes these issues.

**Comment by rjain15** [comment]
I am closing this issue, since I moved to another Mongodb chart from kubernetesio instead of bitnami

**Comment by prydonius** [comment]
@rjain15 in order to help future users, it would be great to know what version and which chart you are using. I'm not sure what you mean since the Monocular chart is pointing to the Helm stable/mongodb chart and not the Bitnami repo, but it is the same chart.

**Comment by nemox** [comment]
Hello, 
I seem to have a similar problem. I deploy mongodb with helm and set values in the values.yaml file.

**Comment by nemox** [comment]
```
 mongodb:
   enabled: true
   image:
     tag: latest
     pullPolicy: IfNotPresent
     debug: true
   mongodbExtraFlags:
   - "--wiredTigerCacheSizeGB=1"
   mongodbRootPassword: root
   mongodbUsername: mongouser
   mongodbPassword: user
   mongodbDatabase: mongobase
   mongodbHostname: hasher-mongodb
   volumePermissions:
     enabled: true
   useStatefulSet: true
   persistence:
     annotations:
       ibm.io/auto-create-bucket: "true"
       ibm.io/auto-delete-bucket: "true"
       ibm.io/bucket: ""
       ibm.io/secret-name: "cos-write-access"
     storageClass: "ibmc-s3fs-standard-regional"
     accessModes:
       - ReadWriteMany
     size: 10Gi
 
```
Firstly, if i I do not set useStatefulSet to true, the annotations from persistence.annotations is not rendered in the annotations of the created PersistenceVolumeClaim.
Further more when I run ```kubectl get pvc```I get this output:
```NAME                    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                  AGE
data-hasher-mongodb-0   Bound    pvc-96481391-db40-49ee-ab57-2e314c407856   10Gi       RWX            ibmc-s3fs-standard-regional   8m36s```

Checkit out the pod with ```kubectl describe pod hasher-mongodb-0```:

```
Name:         hasher-mongodb-0
Namespace:    default
Priority:     0
Node:         10.144.180.104/10.144.180.104
Start Time:   Fri, 06 Mar 2020 20:50:13 +0100
Labels:       app=mongodb
              chart=mongodb-7.8.7
              controller-revision-hash=hasher-mongodb-645f4fd4f9
              release=hasher
              statefulset.kubernetes.io/pod-name=hasher-mongodb-0
Annotations:  kubernetes.io/psp: ibm-privileged-psp
Status:       Pending
IP:           172.30.180.37
IPs:
  IP:           172.30.180.37
Controlled By:  StatefulSet/hasher-mongodb
Init Containers:
  volume-permissions:
    Container ID:  containerd://455d5730bb01b6c67940dbfbf2c87ec8c4ed7652b2d13c91169c51d3b22b6fa3
    Image:         docker.io/bitnami/minideb:buster
    Image ID:      docker.io/bitnami/minideb@sha256:2f430acaa0ffd88454ac330a6843840f1e1204007bf92f8ce7b654fd3b558d68
    Port:          <none>
    Host Port:     <none>
    Command:
      chown
      -R
      1001:1001
      /bitnami/mongodb
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Fri, 06 Mar 2020 20:55:50 +0100
      Finished:     Fri, 06 Mar 2020 20:55:50 +0100
    Ready:          False
    Restart Count:  6
    Environment:    <none>
    Mounts:
      /bitnami/mongodb from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-sdgp9 (ro)
Containers:
  hasher-mongodb:
    Container ID:   
    Image:          docker.io/bitnami/mongodb:latest
    Image ID:       
    Port:           27017/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Liveness:       exec [mongo --eval db.adminCommand('ping')] delay=30s timeout=5s period=10s #success=1 #failure=6
    Readiness:      exec [mongo --eval db.adminCommand('ping')] delay=5s timeout=5s period=10s #success=1 #failure=6
    Environment:
      BITNAMI_DEBUG:                    true
      MONGODB_PASSWORD:                 <set to the key 'mongodb-password' in secret 'hasher-mongodb'>       Optional: false
      MONGODB_ROOT_PASSWORD:            <set to the key 'mongodb-root-password' in secret 'hasher-mongodb'>  Optional: false
      MONGODB_USERNAME:                 mongouser
      MONGODB_SYSTEM_LOG_VERBOSITY:     0
      MONGODB_DISABLE_SYSTEM_LOG:       no
      MONGODB_DATABASE:                 mongobase
      MONGODB_ENABLE_IPV6:              no
      MONGODB_ENABLE_DIRECTORY_PER_DB:  no
      MONGODB_EXTRA_FLAGS:              --wiredTigerCacheSizeGB=1
    Mounts:
      /bitnami/mongodb from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-sdgp9 (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-hasher-mongodb-0
    ReadOnly:   false
  default-token-sdgp9:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-sdgp9
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 600s
                 node.kubernetes.io/unreachable:NoExecute for 600s
Events:
  Type     Reason            Age                     From                     Message
  ----     ------            ----                    ----                     -------
  Warning  FailedScheduling  9m25s (x2 over 9m27s)   default-scheduler        error while running "VolumeBinding" filter plugin for pod "hasher-mongodb-0": pod has unbound immediate PersistentVolumeClaims
  Normal   Scheduled         9m22s                   default-scheduler        Successfully assigned default/hasher-mongodb-0 to 10.144.180.104
  Normal   Created           8m38s (x4 over 9m18s)   kubelet, 10.144.180.104  Created container volume-permissions
  Normal   Started           8m38s (x4 over 9m18s)   kubelet, 10.144.180.104  Started container volume-permissions
  Normal   Pulling           7m55s (x5 over 9m19s)   kubelet, 10.144.180.104  Pulling image "docker.io/bitnami/minideb:buster"
  Normal   Pulled            7m54s (x5 over 9m18s)   kubelet, 10.144.180.104  Successfully pulled image "docker.io/bitnami/minideb:buster"
  Warning  BackOff           4m14s (x25 over 9m15s)  kubelet, 10.144.180.104  Back-off restarting failed container
```
If I run mongodb without volumePermissions I get the error as the other user I get:
```
connecting to: mongodb://127.0.0.1:27017/?gssapiServiceName=mongodb
2020-03-06T19:43:44.075+0000 E QUERY    [js] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed: SocketException: Error connecting to 127.0.0.1:27017 :: caused by :: Connection refused :
connect@src/mongo/shell/mongo.js:344:17
@(connect):2:6
exception: connect failed
```

Any help would be greatly appreciated.
