### ISSUE TITLE
Cannot use monocular behind a proxy

### ISSUE THREAD

**Issue by jroucheton** [helm/monocular#542]
This issue for explaining that we cannot use monocular behind a proxy.

**WHY?**
Because, we cannot add a proxy though values.yaml
The new delivery (1.0) is based on jobs for synchronizing charts repositories.
A first one for the from scratch deployment and another one for the refresh mechanism.
Unfortunately, we cannot configure those jobs with dedicated proxy for downloading charts.

It will be nice to be able to add env vars (HTTP_PROXY, HTTPS_PROXY and NO_PROXY) at values level....

**Comment by willuk2010** [comment]
@jroucheton check this out, 

https://github.com/kubeapps/kubeapps/issues/696

**Comment by jroucheton** [comment]
Thanks @willuk2010 
Nevertheless, this proposal concerns kubeapps.
I hope that we can have the same kind of improvement for [Monocular](https://github.com/helm/monocular).

**Comment by prydonius** [comment]
@jroucheton I think this just requires adding a new value to configure those env vars in the Jobs/CronJobs? Happy to accept a PR that does that!
