### ISSUE TITLE
File not found on nginx.conf

### ISSUE THREAD

**Issue by erihanse** [helm/monocular#544]
We have a kubernetes cluster, and we're trying to install monocular on it. In the monocular-ui container we're getting a `/opt/bitnami/nginx/conf/nginx.conf` file not found. I'm not sure how to troubleshoot this. If I run the image: `docker run --rm -it -p 8080:8080/tcp -p 8443:8443/tcp quay.io/helmpack/monocular-ui:v1.0.0` it works. 

```
➜  monocular kubectl logs monocular-release-monocular-ui-6fd99546c-cvb2c --namespace=erik-test --container=monocular

Welcome to the Bitnami nginx container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-nginx
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-nginx/issues
Send us your feedback at containers@bitnami.com

INFO  ==> Starting nginx...
nginx: [emerg] open() "/opt/bitnami/nginx/conf/nginx.conf" failed (2: No such file or directory)
2018/10/18 08:20:54 [emerg] 21#0: open() "/opt/bitnami/nginx/conf/nginx.conf" failed (2: No such file or directory)
```

**Comment by tompizmor** [comment]
Hi @erihanse,

I am not able to reproduce the issue. Can you reply the following questions about your environment?

- How are you installing Monocular? Using the chart? If so, which version?
- What is your kubernetes cluster? (AKS, GKE, Minikube, ...)
- Did you made any change in the chart templates?
- Are you installing Monocular with any custom parameter?

**Comment by erihanse** [comment]
Managed to solve this. Think many issues arise since root filesystem is read-only. By the way, appreciate the help :+1:
Here are my changes:  
```
diff --git a/chart/monocular/templates/ui-deployment.yaml b/chart/monocular/templates/ui-deployment.yaml
index 8a89b40..8c6d472 100644
--- a/chart/monocular/templates/ui-deployment.yaml
+++ b/chart/monocular/templates/ui-deployment.yaml
@@ -32,6 +32,10 @@ spec:
           initialDelaySeconds: 30
           timeoutSeconds: 5
         volumeMounts:
+          - name: tmp
+            mountPath: /tmp
+          - name: conf
+            mountPath: /opt/bitnami/nginx/conf/
           - name: vhost
             mountPath: /bitnami/nginx/conf/vhosts
           - name: config
@@ -39,6 +43,10 @@ spec:
         resources:
 {{ toYaml .Values.ui.resources | indent 12 }}
       volumes:
+      - name: tmp
+        emptyDir: {}
+      - name: conf
+        emptyDir: {}
       - name: vhost
         configMap:
           name: {{ template "fullname" . }}-ui-vhost
diff --git a/chart/monocular/values.yaml b/chart/monocular/values.yaml
index c4dc3b4..0f0d903 100644
--- a/chart/monocular/values.yaml
+++ b/chart/monocular/values.yaml
@@ -1,7 +1,6 @@
 sync:
   # Image used to perform chart repository syncs
   image:
-    registry: docker.io
     repository: quay.io/helmpack/chart-repo
     tag: v1.0.0
   repos:
@@ -29,8 +28,8 @@ sync:
 # Chartsvc is used to serve chart metadata over a REST API.
 chartsvc:
   image:
-    registry: docker.io
-    repository: quay.io/helmpack/chartsvc
+    registry: quay.io
+    repository: helmpack/chartsvc
     tag: v1.0.0
   service:
     port: 8080
```
Answering your questions anyway for completeness. 
> How are you installing Monocular? Using the chart? If so, which version?

First I tried `helm install monocular/monocular`. At first it said it couldn't find the images, but that I guess will be adressed in #548. To fix these I fetched the chart, `helm fetch monocular/monocular --untar`, and configured the image names.   
> What is your kubernetes cluster? (AKS, GKE, Minikube, ...)

We have an on-prem cluster setup, which our team administers.  
> Did you made any change in the chart templates?

Yes, quite a few. See above.
> Are you installing Monocular with any custom parameter?

No
