### ISSUE TITLE
Migrate chart and search page to new css framework

### ISSUE THREAD

**Issue by migmartri** [helm/monocular#57]
Chart page.

![helm ui](https://cloud.githubusercontent.com/assets/24523/20358378/72e5bf00-abe0-11e6-96c8-7602132f06cb.png)

Search page.
![helm ui](https://cloud.githubusercontent.com/assets/24523/20358427/9b2f6e0c-abe0-11e6-8e6d-4f1f5bc1b25e.png)

**Comment by Angelmmiguel** [comment]
@migmartri I'm working on it :)

**Comment by Angelmmiguel** [comment]
Can you close this @migmartri? I've split this task into #59 and #60. We can discuss about the design on each task
