### ISSUE TITLE
SVG icons are not displayed

### ISSUE THREAD

**Issue by lambertjosh** [helm/monocular#577]
First, thanks for this great project! In doing a bit of testing, our `gitlab` chart uses an SVG for its icon. Unfortunately it is not displayed: https://hub.helm.sh/charts/gitlab/gitlab

According to the spec, SVG's are supported: https://github.com/helm/helm/blob/master/docs/charts.md#the-chartyaml-file

Would be great if SVG's were shown!

**Comment by prydonius** [comment]
Thanks for the bug, this would be really cool! We currently download the icons and post-process them (currently just converting to PNG and resizing to 160x160), so we would need to change this to either convert the SVG to PNG so everything else stays the same, or store the SVGs and display them differently in the frontend. I'm not sure we really need to preserve the SVG, so converting to PNG might be the simplest option, but I'm not sure if there are any side effects from doing that conversion.
