### ISSUE TITLE
Add header to rest of pages in the application

### ISSUE THREAD

**Issue by migmartri** [helm/monocular#58]
This header is only present in the home page. It should be present in all the pages.

It should also add a search bar in the header (how initially was) for pages that are not the home page. 

![selection_033](https://cloud.githubusercontent.com/assets/24523/20358555/13d8c9b6-abe1-11e6-8642-4d8d75fcea80.png)

**Comment by Angelmmiguel** [comment]
![Header](https://cloud.githubusercontent.com/assets/4056725/20380926/29e8abee-aca5-11e6-84be-146adf5b7f92.png)

I moved the search box to the header.

**Comment by Angelmmiguel** [comment]
It's already implemented in https://github.com/helm/monocular/pull/62 :)
