### ISSUE TITLE
Self-signed certificate problem

### ISSUE THREAD

**Issue by ns500** [helm/monocular#585]
time="2018-12-29T02:19:29Z" level=error msg="error requesting repo index" error="Get https://harbor.com/chartrepo/test/index.yaml: x509: certificate signed by unknown authority" url="https://harbor.com/chartrepo/test/index.yaml"
time="2018-12-29T02:19:29Z" level=fatal msg="Can't add chart repository to database: Get https://harbor.com/chartrepo/test/index.yaml: x509: certificate signed by unknown authority"

I tried to add a self-signed certificate to the golang:1.11 image and then rebuild the chart-repo image, but the error was still prompted.

**Comment by ns500** [comment]
I solved this problem by copying the Linux system's root certificate into the images.

**Comment by prydonius** [comment]
@ns500 hmm, the image already pulls in the certs from the golang base image, could this be improved? https://github.com/helm/monocular/blob/master/cmd/chart-repo/Dockerfile#L9

**Comment by ns500** [comment]
> @ns500 hmm, the image already pulls in the certs from the golang base image, could this be improved? https://github.com/helm/monocular/blob/master/cmd/chart-repo/Dockerfile#L9

Ok, I'll try.

**Comment by brunowego** [comment]
I'm solved this rebuilding the image with my certificates. 

Perhaps adding a new attribute passing the cert, like this:

```sh
cat << EOF | helm upgrade monocular monocular/monocular -f ./current-values.yaml -f -
sync:
  repos:
    - name: example
      url: https://chartmuseum.example.com
      schedule: '*/5 * * * *'
      cert: $(cat /etc/ssl/certs/example/ca.crt | base64)
EOF
```
