### ISSUE TITLE
Use self-signed certificate repository

### ISSUE THREAD

**Issue by ns500** [helm/monocular#587]
Rebuild chart-repo images:
1、Generate a self-signed ca certificate
2、Copy your ca certificate to monocular root directory
3、modify Dockerfile file
FROM golang:1.11 as builder
COPY . /go/src/github.com/helm/monocular
WORKDIR /go/src/github.com/helm/monocular
RUN cat ca.crt >> /etc/ssl/certs/ca-certificates.crt
ARG VERSION
RUN CGO_ENABLED=0 go build -a -installsuffix cgo -ldflags "-X main.version=$VERSION" ./cmd/chart-repo
FROM scratch
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /go/src/github.com/helm/monocular/chart-repo /chart-repo
USER 1001
CMD ["/chart-repo"]
4、make -C cmd/chart-repo/ docker-build

**Comment by prydonius** [comment]
@ns500 does this work for you? Note that chart-repo will also read additional CAs from `/usr/local/share/ca-certificates/ca.crt` https://github.com/helm/monocular/commit/2a4cbdcc1e583495e3be2ded3a94a643b504192a#diff-dd464ab7a9989bed9c6a3801d51ade13R50, so you can also mount your custom CA as a configmap into that path

**Comment by ns500** [comment]
Great, thanks for your help.
