### ISSUE TITLE
Design and implement the new Chart page

### ISSUE THREAD

**Issue by Angelmmiguel** [helm/monocular#59]
It includes all the information of a Chart.

**Comment by Angelmmiguel** [comment]
![Chart Details view](https://cloud.githubusercontent.com/assets/4056725/20394203/05af1418-acdf-11e6-9f11-8eb03c7ff75e.png)

To display the Chart data, I split the page in two columns. On the left we have the main information. On the right I included the `Usage` and the `Readme`.

About versions, I listed all the available versions of the Chart. However, I don't see this data in the API response:

```
{
  "attributes": {
    "description": "A Jenkins Helm chart for Kubernetes.",
    "home": "https://jenkins.io/",
    "icon": "https://wiki.jenkins-ci.org/download/attachments/2916393/logo.png",
    "maintainers": [
      {
        "email": "lachlan@deis.com",
        "name": "Lachlan Evenson"
      },
      {
        "email": "viglesias@google.com",
        "name": "Vic Iglesias"
      }
    ],
    "name": "jenkins",
    "repo": "stable",
    "sources": [
      "https://github.com/jenkinsci/jenkins",
      "https://github.com/jenkinsci/docker-jnlp-slave"
    ]
  },
  "id": "stable/jenkins",
  "links": {
    "self": "/v1/charts/stable/jenkins"
  },
  "relationships": {
    "latestChartVersion": {
      "data": {
        "created": "2016-11-14T19:33:21.28681248Z",
        "digest": "65504e3f6127da392b3de36b4798673872840d42a32cc18290d855c34ddf4e7f",
        "urls": [
          "http://storage.googleapis.com/kubernetes-charts/jenkins-0.1.1.tgz"
        ],
        "version": "0.1.1"
      },
      "links": {
        "self": "/v1/charts/stable/jenkins/versions/0.1.1"
      }
    }
  },
  "type": "chart"
}
```

Will this information be included in the API Readme endpoint #31?

**Comment by migmartri** [comment]
Awesome @Angelmmiguel!

The only thing I am not convinced about is the fact that the README content appears in the column on the right.

For me, it feels more natural (maybe after all these years of blog reading) to find the main content on the left and then a sidebar on the right with auxiliar content. 

Thanks!

**Comment by Angelmmiguel** [comment]
I agree with you, the main content should be positioned on the left due to our reading flow. I will update it.

Thanks!

**Comment by migmartri** [comment]
@Angelmmiguel 

I am running into some issues with the latest version of the code.

I am using the bundled docker-compose file and accessing via localhost:4200

```
snack-bar-container.js:4Uncaught TypeError: Cannot read property 'prototype' of undefined
    at __extends (snack-bar-container.js:4)
    at snack-bar-container.js:28
    at Object.<anonymous> (snack-bar-container.js:122)
    at __webpack_require__ (bootstrap 9464e2d…:52)
    at Object.<anonymous> (snack-bar-ref.js:70)
    at __webpack_require__ (bootstrap 9464e2d…:52)
    at Object.<anonymous> (menu.js:40)
    at __webpack_require__ (bootstrap 9464e2d…:52)
    at Object.<anonymous> (icon.js:264)
    at __webpack_require__ (bootstrap 9464e2d…:52)
```

![Uploading Selection_047.png…]()
