### ISSUE TITLE
helm monocular install error DNS-1123 subdomain violation error

### ISSUE THREAD

**Issue by gprashanthkumar** [helm/monocular#596]
I know its reported 5 days back under [593 ](https://github.com/helm/monocular/issues/593)but its closed. so i am raising again

OS : Ubuntu 16. LTS

$ helm version
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}

Its throwing DNS-1123 subdomain violation error

helm install --name=mono monocular/monocular
Error: release mono failed: Ingress.extensions "mono-monocular" is invalid: spec.rules[0].host: Invalid value: "": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is 'a-z0-9?(.a-z0-9?)*')

**Comment by jecho** [comment]
it looks like ingress is enabled by default and you haven’t set any values for it. 

try:
$ helm install --name=mono monocular/monocular --set ingress.enabled=false
