### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mattfarina** [helm/monocular#61]
This may seem like a small detail but what License is the project under? In UI package.json I see MIT. But, aren't most k8s based projects Apache? Since there is no license file I wasn't sure the intent. So, I don't know what I'm consuming nor what I might contribute under.

**Comment by technosophos** [comment]
Yeah, Apache v2 is what we'd need to get this into incubator.

**Comment by migmartri** [comment]
@mattfarina, thanks for bringing this to our attention and sorry for the late response.

@technosophos thanks!
