### ISSUE TITLE
Ingress issues with ingress-nginx > 0.22

### ISSUE THREAD

**Issue by cpoole** [helm/monocular#610]
According to https://github.com/kubernetes/ingress-nginx/tree/master/docs/examples/rewrite#rewrite-target

The rewrite target now requires the capture groups to be explicitly declared...

But now the paths will only work with ingress-nginx. this wont work for istio or traefik.

I can parameterize this if there's interest?

**Comment by prydonius** [comment]
Shame it's not backwards compatible - thanks!
