### ISSUE TITLE
hub.helm.sh shows same date for all chart releases

### ISSUE THREAD

**Issue by rimusz** [helm/monocular#618]
https://hub.helm.sh shows same release date for all chart releases 
![Screenshot 2019-03-25 18 36 12](https://user-images.githubusercontent.com/5215395/54945156-1a026d00-4f2d-11e9-9378-e551284ecb08.png)

**Comment by arapulido** [comment]
@rimusz this comes from your chart repo information: https://charts.rimusz.net/index.yaml You can see that the date is the same for every version. Monocular just renders what's in there. You can fix the index.yaml to fix it.

**Comment by rimusz** [comment]
gotcha, thanks
