### ISSUE TITLE
Search results layout

### ISSUE THREAD

**Issue by migmartri** [helm/monocular#65]
The search results layout needs to be adapted to the new UI framework.

![selection_051](https://cloud.githubusercontent.com/assets/24523/21867875/0c4eae22-d805-11e6-9b78-e5120622ff6e.png)

cc/ @Angelmmiguel

**Comment by Angelmmiguel** [comment]
I already implemented it in my local branch: https://github.com/Angelmmiguel/monocular/tree/60-chart-list.

![Search view](https://cloud.githubusercontent.com/assets/4056725/21886538/835c6be6-d8bc-11e6-948c-efefa5edcdcc.png)

However, I need to close #66 before create the PR.
