### ISSUE TITLE
Update to Helm 3 the 'helm install' instruction

### ISSUE THREAD

**Issue by carrodher** [helm/monocular#659]
The `helm install` command doesn't work in Helm 3.

![Screen Shot 2020-02-12 at 14 17 03](https://user-images.githubusercontent.com/13216600/74338491-95b61400-4da2-11ea-8d85-3ff632d32d72.png)

Using this instruction:
```bash
▶ helm install bitnami/airflow --version 4.3.1
Error: must either provide a name or specify --generate-name
```
My proposal is to add the `--generate-name` flag:
```bash
▶ helm install bitnami/airflow --version 4.3.1 --generate-name
```

Then the other instructions depend on the `README.md` (not maintained by Helm itself), but it would be nice to, at least, update to Helm 3 the common sections.

**Comment by andyfeller** [comment]
While I wouldn't want to use `--generate-name` for my own use cases, I want quickstart guides to literally be copy and paste friendly.  Ran into this myself and hesitate pointing people toward Helm Hub if this is the behavior.
