### ISSUE TITLE
Swagger.yml does not validate with 2.0 spec

### ISSUE THREAD

**Issue by migmartri** [helm/monocular#72]
```
$ swagger validate swagger.yml 
The swagger spec at "swagger.yml" is invalid against swagger specification 2.0. see errors :
- definitions.chart.properties.icon.minLenth in body is a forbidden property
- definitions.chart.properties.repo.minLenth in body is a forbidden property
```

**Comment by prydonius** [comment]
Looks like this is just a misspelling, should be an easy first contribution :)

**Comment by Dean-Coakley** [comment]
@prydonius I was going to pick up this issue but looks like the file mentioned was deleted in: https://github.com/helm/monocular/pull/518

Is this to be closed? Or can you give me directions on how to proceed?

**Comment by prydonius** [comment]
@Dean-Coakley indeed, the old API server that used the swagger spec has been replaced. Sorry for the confusion, I'll close this out!
