### ISSUE TITLE
Be able to configure backendURL via env variables

### ISSUE THREAD

**Issue by migmartri** [helm/monocular#73]
Currently, the UI has the backend domain and port [hardcoded](https://github.com/helm/monocular/blob/master/src/ui/src/app/config.ts#L6). We must find a way to set those values via env variables. 

In theory this is feasible using webpack but last time I looked into it I could not find a simple solution since angular-ui bundles its own webpack configuration and did not allow extending it.

**Comment by Angelmmiguel** [comment]
Webpack configuration won't be exposed in `angular-cli` project. You can check [this issue](https://github.com/angular/angular-cli/issues/1656#issuecomment-249921747).

However, I think we can create a `config.json` file and add it to the `.gitignore`. `config.ts` will read that file and override the default configuration with the specific values defined in the JSON file.

What do you think?
