### ISSUE TITLE
Set proper usage instructions

### ISSUE THREAD

**Issue by migmartri** [helm/monocular#80]
For example this is not valid.

```
 helm install incubator/consul --version 0.1.3
```

We might want to show how to add the incubator repo before.

@prydonius what's your take here?

**Comment by prydonius** [comment]
For consul, we do: https://github.com/kubernetes/charts/tree/master/incubator/consul#installing-the-chart. Some charts are missing it though. Also, that URL needs to be updated to https://kubernetes-charts-incubator.storage.googleapis.com

**Comment by migmartri** [comment]
Assuming that adding twice the same repository does not crash we should:

* If stable
  * Show helm install for the specific version
  * remove the /stable prefix
* else
  * Show information about how to add the repository
  * Show helm install for the specific version

**Comment by migmartri** [comment]
I'd recommend to wait until https://github.com/helm/monocular/pull/74#partial-pull-merging is merged since it contains some changes in the same component
