### ISSUE TITLE
Normalize Icons and descriptions expectations on charts' end

### ISSUE THREAD

**Issue by migmartri** [helm/monocular#93]
## Description

Currently, the UI uses the description for searching capabilities, which means that descriptions like `Chart for MariaDB` are poor. 

We need to add something more descriptive and useful like:

```
MariaDB is a fast, reliable, scalable, and easy to use open-source relational database system. MariaDB Server is intended for mission-critical, heavy-load production systems as well as for embedding into mass-deployed software.
``` 

## Icons

Most of the charts do not have icons or they are too small. We need to add those icons upstream.

![selection_106](https://cloud.githubusercontent.com/assets/24523/22660786/b2b3531a-ec57-11e6-8ebb-737d0117bfbe.png)

### chaoskube (stable) 
- [x] Description 
- [x] Icon 
### chronograf (stable) 
- [x] Description 
- [x] Icon 
### cockroachdb (stable) 
- [x] Description 
- [x] Icon 
### concourse (stable) 
- [x] Description 
- [x] Icon 
### datadog (stable) 
- [x] Description 
- [x] Icon 
### dokuwiki (stable) 
- [x] Description 
- [x] Icon 
### drupal (stable) 
- [x] Description 
- [x] Icon 
### etcd-operator (stable) 
- [x] Description 
- [x] Icon 
### factorio (stable) 
- [x] Description 
- [x] Icon 
### ghost (stable) 
- [x] Description 
- [x] Icon 
### gitlab-ce (stable) 
- [x] Description 
- [x] Icon 
### grafana (stable) 
- [x] Description 
- [x] Icon 
### influxdb (stable) 
- [x] Description 
- [x] Icon 
### jasperreports (stable) 
- [x] Description 
- [x] Icon 
### jenkins (stable) 
- [x] Description 
- [x] Icon 
### joomla (stable) 
- [x] Description 
- [x] Icon 
### kapacitor (stable) 
- [x] Description 
- [x] Icon 
### kube-lego (stable) 
- [x] Description 
- [x] Icon 
### kube2iam (stable) 
- [x] Description 
- [x] Icon 
### linkerd (stable) 
- [x] Description 
- [x] Icon 
### magento (stable) 
- [x] Description 
- [x] Icon 
### mariadb (stable) 
- [x] Description 
- [x] Icon 
### mediawiki (stable) 
- [x] Description 
- [x] Icon 
### memcached (stable) 
- [x] Description 
- [x] Icon 
### minecraft (stable) 
- [x] Description 
- [x] Icon 
### minio (stable) 
- [x] Description 
- [x] Icon 
### mongodb (stable) 
- [x] Description 
- [x] Icon 
### mysql (stable) 
- [x] Description 
- [x] Icon 
### nginx-lego (stable) 
- [x] Description 
- [x] Icon 
### odoo (stable) 
- [x] Description 
- [x] Icon 
### opencart (stable) 
- [x] Description 
- [x] Icon 
### openvpn (stable) 
- [x] Description 
- [x] Icon 
### orangehrm (stable) 
- [x] Description 
- [x] Icon 
### osclass (stable) 
- [x] Description 
- [x] Icon 
### owncloud (stable) 
- [x] Description 
- [x] Icon 
### phabricator (stable) 
- [x] Description 
- [x] Icon 
### phpbb (stable) 
- [x] Description 
- [x] Icon 
### postgresql (stable) 
- [x] Description 
- [x] Icon 
### prestashop (stable) 
- [x] Description 
- [x] Icon 
### prometheus (stable) 
- [x] Description 
- [x] Icon 
### rabbitmq (stable) 
- [x] Description 
- [x] Icon 
### redis (stable) 
- [x] Description 
- [x] Icon 
### redmine (stable) 
- [x] Description 
- [x] Icon 
### sapho (stable) 
- [x] Description 
- [x] Icon 
### sensu (stable) 
- [x] Description 
- [x] Icon 
### spark (stable) 
- [x] Description 
- [x] Icon 
### spartakus (stable) 
- [x] Description 
- [x] Icon 
### spinnaker (stable) 
- [x] Description 
- [x] Icon 
### sumokube (stable) 
- [x] Description 
- [x] Icon 
### telegraf (stable) 
- [x] Description 
- [x] Icon 
### testlink (stable) 
- [x] Description 
- [x] Icon 
### traefik (stable) 
- [x] Description 
- [x] Icon 
### uchiwa (stable) 
- [x] Description 
- [x] Icon 
### wordpress (stable) 
- [x] Description 
- [x] Icon 

### artifactory (incubator) 
- [x] Description 
- [x] Icon 
### consul (incubator) 
- [x] Description 
- [x] Icon 
### elasticsearch (incubator) 
- [x] Description 
- [x] Icon 
### etcd (incubator) 
- [x] Description 
- [x] Icon 
### kafka (incubator) 
- [x] Description 
- [x] Icon 
### kube-ops-view (incubator) 
- [x] Description 
- [x] Icon 
### mongodb-replicaset (incubator) 
- [x] Description 
- [x] Icon 
### patroni (incubator) 
- [x] Description 
- [x] Icon 
### tensorflow-inception (incubator) 
- [x] Description 
- [x] Icon 
### zookeeper (incubator) 
- [x] Description 
- [x] Icon

**Comment by migmartri** [comment]
cc/ @prydonius @Angelmmiguel

**Comment by Angelmmiguel** [comment]
Great work @migmartri!!!! :+1:
