### ISSUE TITLE
/charts page should support repository filtering

### ISSUE THREAD

**Issue by migmartri** [helm/monocular#96]
`/charts` should support `/charts/:repo`

- [ ] Add those routes pointing to the same component
- [ ] Change SEO metadata to show ":repo charts"
- [ ] Use API endpoint to load those charts instead of client side filtering.

**Comment by Angelmmiguel** [comment]
Should I remove the filter from the top bar or redirect the user to these endpoints when he changes the selector? Also, is the API Endpoint ready?

**Comment by migmartri** [comment]
> Should I remove the filter from the top bar or redirect the user to these endpoints when he changes the selector? 

I think that we should redirect to it.

> Also, is the API Endpoint ready?

Yes, it is.
